# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ImportedItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, dictionary: str=None, key: str=None, status: str=None):  # noqa: E501
        """ImportedItem - a model defined in Swagger

        :param dictionary: The dictionary of this ImportedItem.  # noqa: E501
        :type dictionary: str
        :param key: The key of this ImportedItem.  # noqa: E501
        :type key: str
        :param status: The status of this ImportedItem.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'dictionary': str,
            'key': str,
            'status': str
        }

        self.attribute_map = {
            'dictionary': 'dictionary',
            'key': 'key',
            'status': 'status'
        }
        self._dictionary = dictionary
        self._key = key
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'ImportedItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImportedItem of this ImportedItem.  # noqa: E501
        :rtype: ImportedItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dictionary(self) -> str:
        """Gets the dictionary of this ImportedItem.

        Řízený slovník  # noqa: E501

        :return: The dictionary of this ImportedItem.
        :rtype: str
        """
        return self._dictionary

    @dictionary.setter
    def dictionary(self, dictionary: str):
        """Sets the dictionary of this ImportedItem.

        Řízený slovník  # noqa: E501

        :param dictionary: The dictionary of this ImportedItem.
        :type dictionary: str
        """

        self._dictionary = dictionary

    @property
    def key(self) -> str:
        """Gets the key of this ImportedItem.

        Identifikátor deskriptoru  # noqa: E501

        :return: The key of this ImportedItem.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this ImportedItem.

        Identifikátor deskriptoru  # noqa: E501

        :param key: The key of this ImportedItem.
        :type key: str
        """

        self._key = key

    @property
    def status(self) -> str:
        """Gets the status of this ImportedItem.

        Stav importu  # noqa: E501

        :return: The status of this ImportedItem.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this ImportedItem.

        Stav importu  # noqa: E501

        :param status: The status of this ImportedItem.
        :type status: str
        """
        allowed_values = ["added", "replaced", "rejected"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
