# generated by fastapi-codegen:
#   filename:  swagger.yaml
#   timestamp: 2025-01-26T15:24:01+00:00

from __future__ import annotations

import logging
from contextlib import asynccontextmanager
from typing import List, Union, Annotated

from beanie import init_beanie
from fastapi import FastAPI, Path, Query, Body, Depends
from fastapi.requests import Request
from fastapi.responses import JSONResponse
from motor.motor_asyncio import AsyncIOMotorClient

from api.commons import create_query, update_changed_values
from api.dependencies import header_scheme, is_api_authorized
from api.models import Descriptor, ReplyImported, ApiError, DescriptorDb, ErrorModel, DescriptorBase, ImportedItem, \
    StatusEnum, DescriptorValue
from init import APP_NAME, VERSION, CONFIG, DEFAULT_AGENDA, MONGO_CONNECTION_STRING, CC, LOG, API_ROOT_PATH

logging.basicConfig(
    format='%(asctime)s,%(msecs)03d %(levelname)-8s [%(filename)s:%(lineno)d] %(message)s',
    datefmt='%Y-%m-%d:%H:%M:%S',
    level=logging.DEBUG)

LOGGER = logging.getLogger(__name__)
# LOGGER = LOG.logger


@asynccontextmanager
async def lifespan(api: FastAPI):
    # Startup
    db_name = CONFIG[DEFAULT_AGENDA]['database']
    api.mongodb_client = AsyncIOMotorClient(MONGO_CONNECTION_STRING)
    api.database = api.mongodb_client.get_database(db_name)
    ping_response = await api.database.command("ping")
    if int(ping_response["ok"]) != 1:
        CC.config['mongo']['status'] = 'RED'
        CC.store()
        LOGGER.error("Problem connecting to database cluster.")
        raise Exception("Problem connecting to database cluster.")
    else:
        await init_beanie(
            database=api.mongodb_client[db_name],
            document_models=[DescriptorDb])
        # info("Connected to database cluster.")
        LOGGER.info(f"Connected to database cluster.")
        CC.config['mongo']['status'] = 'GREEN'
        CC.store()
    yield
    # Shutdown
    CC.config['mongo']['status'] = 'RED'
    CC.store()
    api.mongodb_client.close()


app = FastAPI(
    lifespan=lifespan,
    title=f"{APP_NAME} verze: {VERSION}",
    summary="Správa řízených slovníků",
    description='REST API of the SYSNET managed dictionaries (code lists) system. \nPrimarily designed for the CITES Registry.\n',
    contact={
        'name': 'SYSNET s.r.o.',
        'url': 'https://sysnet.cz',
        'email': 'info@sysnet.cz',
    },
    license={
        'name': 'GNU Affero General Public License v3.0',
        'url': 'https://www.gnu.org/licenses/agpl-3.0.html',
    },
    version='2.0.0',
    openapi_tags=[
        {"name": "info", "description": "Informace o službě"},
        {"name": "admins", "description": "Operace pro správce"},
        {"name": "public", "description": "Operace pro veřejné uživatele"},
    ],
    root_path=f"/{API_ROOT_PATH}"
)

LOGGER.info(f"{__name__} - API is starting up")


@app.exception_handler(ApiError)
async def uvicorn_exception_handler(request: Request, exc: ApiError):
    msg = f"{request.client.host}: {exc.message}"
    LOGGER.error(f"{__name__} - {exc.code}: {msg}")
    return JSONResponse(
        status_code=exc.code,
        content={"message": msg},
    )


@app.middleware("http")
async def log_requests(request: Request, call_next):
    LOGGER.info(f"{__name__}.http - Request: {request.method} {request.url}")

    # Protokolování těla požadavku (pokud chcete)
    body = await request.body()
    LOGGER.debug(f"{__name__}.http - Request body: {body}")
    response = await call_next(request)

    # Protokolování odpovědi
    LOGGER.info(f"{__name__}.http - Response status: {response.status_code}")
    return response


@app.delete(
    path='/descriptor/{dictionary}/{key}',
    response_model=bool,
    responses={'default': {'model': ErrorModel}},
    summary='Odstraní deskriptor',
    tags=['admins']
)
async def descriptor_delete(
        dictionary: Annotated[
            str,
            Path(title='Kód slovníku', description='Kód řízeného slovníku')],
        key: Annotated[
            str,
            Path(title='Kód deskriptoru', description='Kód deskriptoru z řízeného slovníku')],
        api_key: str = Depends(header_scheme)
) -> Union[bool, ErrorModel]:
    if not is_api_authorized(key=api_key):
        raise ApiError(code=403, message='Forbidden')
    LOGGER.info(f'DELETE /descriptor')
    if dictionary in [None, '']:
        raise ApiError(code=400, message='Missing dictionary')
    if key in [None, '']:
        raise ApiError(code=400, message='Missing key')
    reply = await DescriptorDb.by_key(dictionary=dictionary, key=key)
    if not reply:
        LOGGER.info(f"DELETE /descriptor/{dictionary}/{key} NOT FOUND")
    LOGGER.info(f"DELETE /descriptor/{dictionary}/{key} FOUND")
    reply1 = await reply.delete(None)
    return reply1.acknowledged


@app.get(
    path='/descriptor/{dictionary}/{key}',
    response_model=Descriptor,
    responses={'default': {'model': ErrorModel}},
    summary='Vrátí konkrétní deskriptor',
    tags=['public'])
async def descriptor_get(
        dictionary: Annotated[
            str,
            Path(title='Kód slovníku', description='Kód řízeného slovníku')],
        key: Annotated[
            str,
            Path(title='Kód deskriptoru', description='Kód deskriptoru z řízeného slovníku')]
) -> Union[Descriptor, ErrorModel]:
    LOGGER.info(f'GET /descriptor')
    if dictionary in [None, '']:
        raise ApiError(code=400, message='Missing dictionary')
    if key in [None, '']:
        raise ApiError(code=400, message='Missing key')
    reply = await DescriptorDb.by_key(dictionary=dictionary, key=key)
    if not reply:
        LOGGER.info(f"GET /descriptor/{dictionary}/{key} NOT FOUND")
    LOGGER.info(f"GET /descriptor/{dictionary}/{key} FOUND")
    out = reply.document
    return out


@app.get(
    path='/descriptor/{dictionary}',
    response_model=List[Descriptor],
    responses={'default': {'model': ErrorModel}},
    summary='Prohledává slovník (autocomplete)',
    tags=['public'])
async def descriptor_get_dictionary_list(
        dictionary: Annotated[
            str,
            Path(title='Kód slovníku', description='Kód řízeného slovníku')],
        query: Annotated[
            Union[str, None], Query(title='Vyhledávaný text', description='Text k vyhledání')] = None,
        key: Annotated[
            Union[str, None], Query(title='Vyhledávaný klíč', description='Klíčové slovo k vyhledání')] = None,
        lang: Annotated[
            Union[str, None], Query(title='Jazyk deskriptoru', description='Jazyk deskriptoru k vyhledání')] = None,
        active: Annotated[
            Union[bool, None], Query(title='Aktivní/neaktivní deskriptory', description='Aktivní/neaktivní deskriptory k vyhledání')] = None,
        skip: Annotated[
            Union[int, None], Query(title='Počet přeskočených výsledků')] = None,
        limit: Annotated[
            Union[int, None], Query(title='Maximální počet vrácených výsledků')] = None,
) -> Union[List[Descriptor], ErrorModel]:
    if dictionary in [None, '']:
        raise ApiError(code=400, message='Missing dictionary')
    if skip is None:
        skip = 0
    if limit is None:
        limit = 999
    query, paging, sort = create_query(dictionary=dictionary, key=key, lang=lang, active=active, search=query, skip=skip, limit=limit)
    reply = await DescriptorDb.by_query(query=query, paging=paging, sort=sort)
    if reply is None or not bool(reply):
        raise ApiError(code=404, message='Nothing found')
    if reply.count == 0:
        raise ApiError(code=404, message='Nothing found')
    return reply


@app.patch(
    path='/descriptor/activate/{dictionary}/{key}',
    response_model=Descriptor,
    responses={'default': {'model': ErrorModel}},
    summary='Aktivuje/deaktivuje deskriptor',
    tags=['admins']
)
async def descriptor_patch_activate(
        dictionary: Annotated[
            str,
            Path(title='Kód slovníku', description='Kód řízeného slovníku')],
        key: Annotated[
            str,
            Path(title='Kód deskriptoru', description='Kód deskriptoru z řízeného slovníku')],
        doit: Annotated[
            bool,
            Query(
                title='Aktivační proměnná',
                description='Aktivuje/Deaktivuje deskriptor')] = True,
        api_key: str = Depends(header_scheme)
) -> Union[Descriptor, ErrorModel]:
    if not is_api_authorized(key=api_key):
        raise ApiError(code=403, message='Forbidden')
    LOGGER.info(f'PATCH /descriptor/activate')
    if dictionary in [None, '']:
        raise ApiError(code=400, message='Missing dictionary')
    if key in [None, '']:
        raise ApiError(code=400, message='Missing key')
    reply = await DescriptorDb.by_key(dictionary=dictionary, key=key)
    if not reply:
        LOGGER.info(f"PATCH /descriptor/activate/{dictionary}/{key} NOT FOUND")
    LOGGER.info(f"PATCH /descriptor/activate/{dictionary}/{key} FOUND")
    reply1 = await reply.activate(doit=doit)
    out = reply1.document
    return out


@app.post(
    path='/descriptor/{dictionary}',
    response_model=None,
    responses={'default': {'model': ErrorModel}},
    summary='Přidá nový deskriptor',
    tags=['admins']
)
async def descriptor_post(
        dictionary: Annotated[
            str,
            Path(title='Kód slovníku', description='Kód řízeného slovníku')],
        body: Annotated[
            DescriptorBase,
            Body(title='Data deskriptoru')] = None,
        api_key: str = Depends(header_scheme)
) -> Union[Descriptor, ErrorModel]:
    if not is_api_authorized(key=api_key):
        raise ApiError(code=403, message='Forbidden')
    LOGGER.info(f'POST /descriptor')
    if dictionary in [None, '']:
        raise ApiError(code=400, message='Missing dictionary')
    if body is None:
        raise ApiError(code=400, message='Missing data')
    if body.key in [None, '']:
        raise ApiError(code=400, message=f"Illegal or missing key")
    key = body.key
    reply = await DescriptorDb.by_key(dictionary=dictionary, key=key)
    if reply:
        LOGGER.info(f"POST /descriptor/{dictionary}/{key} FOUND")
        raise ApiError(code=404, message=f"Descriptor {dictionary}/{key} already exist")
    try:
        b1 = DescriptorBase.model_dump(body)
        dbdoc = DescriptorDb(**b1)
        # await DescriptorDb(values=dbdoc.values).insert_one(dbdoc)
        await DescriptorDb.insert_one(dbdoc)
        out = dbdoc.document
        LOGGER.info(f'POST /descriptor/{dictionary} done: {str(dbdoc.identifier)}')
        return out
    except Exception as e:
        LOGGER.error(f'POST /descriptor/{dictionary} FAILED: {str(e)}')
        raise ApiError(code=500, message=str(e))


@app.put(
    path='/descriptor/{dictionary}/{key}',
    response_model=Descriptor,
    responses={'default': {'model': ErrorModel}},
    summary='Aktualizuje deskriptor',
    tags=['admins']
)
async def descriptor_put(
        dictionary: Annotated[
            str,
            Path(title='Kód slovníku', description='Kód řízeného slovníku')],
        key: Annotated[
            str,
            Path(title='Kód deskriptoru', description='Kód deskriptoru z řízeného slovníku')],
        body: Annotated[
            DescriptorBase,
            Body(title='Data deskriptoru')] = None,
        api_key: str = Depends(header_scheme)
) -> Union[Descriptor, ErrorModel]:
    if not is_api_authorized(key=api_key):
        raise ApiError(code=403, message='Forbidden')
    LOGGER.info(f'PUT /descriptor')
    if dictionary in [None, '']:
        raise ApiError(code=400, message='Missing dictionary')
    LOGGER.debug(f'PUT /descriptor/{dictionary}')
    if key in [None, '']:
        raise ApiError(code=400, message='Missing key')
    LOGGER.debug(f'PUT /descriptor/{dictionary}/{key}')
    if body is None:
        raise ApiError(code=400, message='Missing data')
    LOGGER.debug(f'PUT /descriptor/{dictionary}/{key} - BODY: {type(body)} ')
    if body.key in [None, '']:
        body.key = key
    if body.key != key:
        raise ApiError(code=400, message=f"Illegal key: {key} != {body.key}")
    vl = []
    for v in body.values:
        LOGGER.debug(f'PUT /descriptor/{dictionary}/{key} - VALUES: {type(v)} ')
        if isinstance(v, dict):
            dv = DescriptorValue(**v)
            vl.append(dv)
    if vl:
        body.values = vl
    reply = await DescriptorDb.by_key(dictionary=dictionary, key=key)
    if not reply:
        LOGGER.info(f"PUT /descriptor/{dictionary}/{key} NOT FOUND")
    LOGGER.info(f"PUT /descriptor/{dictionary}/{key} FOUND")
    LOGGER.debug(f'PUT /descriptor/{dictionary}/{key} - REPLY: {type(reply)} ')
    b = reply.model_dump()
    body_old = DescriptorBase(**b)
    dict_old = body_old.model_dump()
    dict_new = body.model_dump()
    update_changed_values(reply, dict_old, dict_new)
    vl2 = []
    for v2 in reply.values:
        LOGGER.debug(f'PUT /descriptor/{dictionary}/{key} - VALUES2: {type(v2)} ')
        if isinstance(v2, dict):
            dv2 = DescriptorValue(**v2)
            vl2.append(dv2)
    if vl2:
        reply.values = vl2
    reply1 = await reply.replace(None)
    if reply1 is None:
        raise ApiError(code=500, message=f"Descriptor '{dictionary}/{key}' cannot be updated")
    LOGGER.info(f"PUT /descriptor/{dictionary}/{key}: {type(reply1)} ")
    out = reply1.document
    LOGGER.info(f"PUT /descriptor/{dictionary}/{key} DONE: {type(out)} ")
    return out


@app.get(
    path='/export',
    response_model=List[DescriptorBase],
    responses={'default': {'model': ErrorModel}},
    summary='Exportuje všechny data jako JSON',
    tags=['admins'])
async def export_all(api_key: str = Depends(header_scheme)) -> Union[List[DescriptorBase], ErrorModel]:
    LOGGER.info(f'GET /export')
    if not is_api_authorized(key=api_key):
        raise ApiError(code=403, message='Forbidden')
    try:
        out = await DescriptorDb.export_all()
        if out is None or not bool(out):
            raise ApiError(code=404, message='Nothing found')
        LOGGER.error(f'GET /export done: {len(out)}')
        return out
    except Exception as e:
        LOGGER.error(f'GET /export FAILED: {str(e)}')
        raise ApiError(code=500, message=str(e))


@app.get(
    path='/export/{dictionary}',
    response_model=List[DescriptorBase],
    responses={'default': {'model': ErrorModel}},
    summary='Exportuje jeden slovník jako JSON',
    tags=['admins'])
async def export_dictionary(
        dictionary: Annotated[
            str,
            Path(title='Kód slovníku', description='Kód řízeného slovníku')],
        api_key: str = Depends(header_scheme)
) -> Union[List[DescriptorBase], ErrorModel]:
    if not is_api_authorized(key=api_key):
        raise ApiError(code=403, message='Forbidden')
    LOGGER.info(f'GET /export')
    if dictionary in [None, '']:
        raise ApiError(code=400, message='Missing dictionary')
    try:
        out = await DescriptorDb.export_dictionary(dictionary=dictionary)
        if out is None or not bool(out):
            raise ApiError(code=404, message='Nothing found')
        LOGGER.error(f'GET /export/{dictionary} done: {len(out)}')
        return out
    except Exception as e:
        LOGGER.error(f'GET /export/{dictionary} FAILED: {str(e)}')
        raise ApiError(code=500, message=str(e))


@app.post(
    path='/import',
    response_model=ReplyImported,
    responses={'default': {'model': ErrorModel}},
    summary='Importuje deskriptory do různých slovníků',
    tags=['admins']
)
async def import_descriptors(
        replace: Annotated[Union[bool, None], Path(title='Nahradit původní hodnoty')] = None,
        body: Annotated[List[DescriptorBase], Body(title='Seznam deskriptorů')] = None,
        api_key: str = Depends(header_scheme)
) -> Union[ReplyImported, ErrorModel]:
    if not is_api_authorized(key=api_key):
        raise ApiError(code=403, message='Forbidden')
    if replace is None:
        replace = False
    if body is None:
        raise ApiError(code=400, message='Missing body')
    if not body:
        raise ApiError(code=400, message='Data is empty')
    out = ReplyImported(count_added=0, count_rejected=0, count_replaced=0, count_error=0)
    out.added = []
    out.replaced = []
    out.rejected = []
    out.error = []
    i = 0
    for item in body:
        imp = ImportedItem(dictionary=item.dictionary, key=item.key, status=None)
        i += 1
        try:
            reply = await DescriptorDb.by_key(dictionary=imp.dictionary, key=item.key)
            if reply is None:
                b1 = DescriptorBase.model_dump(item)
                dbdoc = DescriptorDb(**b1)
                await DescriptorDb.insert_one(dbdoc)
                imp.status = StatusEnum.ADDED
                out.count_added += 1
                out.added.append(imp)
            else:
                if replace:
                    reply.key_alt = item.key_alt
                    reply.active = item.active
                    reply.values = item.values
                    await reply.replace(None)
                    imp.status = StatusEnum.REPLACED
                    out.count_replaced += 1
                    out.replaced.append(imp)
                else:
                    imp.status = StatusEnum.REJECTED
                    out.count_rejected += 1
                    out.rejected.append(imp)
        except Exception as e:
            imp.status = StatusEnum.ERROR
            out.count_error += 1
            out.error.append(imp)
            LOGGER.error(f'IMPORT item {i} FAILED: {str(e)}')
    return out


@app.get(
    path='/info',
    response_model=dict,
    summary='Vrací servisní informace',
    responses={'404': {'model': ErrorModel}, 'default': {'model': ErrorModel}},
    tags=['info'],)
async def info_api_get() -> Union[JSONResponse, ErrorModel]:
    """
    Vrací servisní informace
    """
    out = {
        'status': 'RED',
        'mongo': {'status': CONFIG['mongo']['status']},
    }
    green = 0
    yellow = 0
    red = 0
    for k, v in out.items():
        if isinstance(v, dict):
            if 'status' in v:
                if v['status'] == 'GREEN':
                    green += 1
                elif v['status'] == 'YELLOW':
                    yellow += 1
                else:
                    red += 1
    if green == 1:
        out['status'] = 'GREEN'
    elif red == 0:
        out['status'] = 'YELLOW'
    return JSONResponse(status_code=200, content=out)


@app.head(
    path='/info',
    response_model=None,
    responses={'default': {'model': ErrorModel}},
    summary='Vrací informaci o dostupnosti služby',
    tags=['info'],)
async def info_api_head() -> Union[None, ErrorModel]:
    """
    Vrací informaci o dostupnosti služby
    """
    return None
