# generated by fastapi-codegen:
#   filename:  resources/swagger.yaml
#   timestamp: 2025-01-26T15:24:01+00:00

from __future__ import annotations

import logging
from datetime import datetime
from enum import Enum
from typing import List, Optional, Union, Annotated
from uuid import UUID, uuid4

import pymongo
from beanie import Document, before_event, Insert, Replace, Update, SaveChanges
from pydantic import BaseModel, Field, RootModel
from pymongo import IndexModel
from sysnet_pyutils.utils import local_now

from init import COLLATION


class ApiError(Exception):
    def __init__(self, code: int = 500, message: str = None):
        self.code = code
        self.message = message


class ErrorModel(BaseModel):
    code: int
    message: str


class StatusEnum(Enum):
    ADDED = 'added'
    REPLACED = 'replaced'
    REJECTED = 'rejected'
    ERROR = 'failed'

    @classmethod
    def has_value(cls, value):
        return value in cls._value2member_map_


class ImportedItem(BaseModel):
    dictionary: Annotated[Union[str, None], Field(description='Řízený slovník', examples=['country'])]
    key: Annotated[Union[str, None], Field(description='Identifikátor deskriptoru', examples=['AT'])]
    status: Annotated[Union[StatusEnum, None], Field(description='Stav importu', examples=['replaced'])]
    # dictionary: Optional[str] = Field(None, description='Řízený slovník', examples=['country'])
    # key: Optional[str] = Field(None, description='Identifikátor deskriptoru', examples=['AT'])
    # status: Optional[StatusEnum] = Field(None, description='Stav importu', examples=['replaced'])


class ReplyImported(BaseModel):
    count_added: Optional[int] = Field(0, description='počet nově přidaných deskriptorů', examples=[25])
    count_replaced: Optional[int] = Field(0, description='počet nahrazených deskriptorů', examples=[5])
    count_rejected: Optional[int] = Field(0, description='počet zamítnutých deskriptorů', examples=[10])
    count_error: Optional[int] = Field(0, description='počet chyb importu', examples=[1])
    added: Optional[List[ImportedItem]] = None
    replaced: Optional[List[ImportedItem]] = None
    rejected: Optional[List[ImportedItem]] = None
    error: Optional[List[ImportedItem]] = None


class DescriptorValue(BaseModel):
    lang: Optional[str] = Field(..., description='jazyk hodnoty deskriptoru', examples=['cs'])
    value: Optional[str] = Field(..., description='Hodnota deskriptoru pro jazyk', examples=['Rakousko'])
    value_alt: Optional[str] = Field(..., description='Alternativní hodnota deskriptoru pro jazyk', examples=['Rakouská spolková republika'])


class DescriptorBase(BaseModel):
    key: Optional[str] = Field(..., description='Hlavní klíč deskriptoru', examples=['AT'])
    key_alt: Optional[str] = Field(..., description='Alternativní klíč deskriptoru', examples=['AUT'])
    dictionary: Optional[str] = Field(..., description='Kód řízeného slovníku', examples=['country'])
    active: Optional[bool] = Field(..., description='Descriptor is active', examples=[True])
    values: Optional[List[DescriptorValue]] = Field(..., description='Seznam hodnot deskriptoru')


class Descriptor(DescriptorBase):
    identifier: UUID = Field(..., description='Identifikátor deskriptoru')


class DescriptorDb(Document, Descriptor):
    identifier: UUID = Field(
        default_factory=uuid4,
        description='Document unique identifier',
        examples=['123e4567-e89b-12d3-a456-426614174000'])
    version: int = 0
    timestamp: datetime = local_now()

    class Settings:
        name = "descriptor"
        indexes = [
            IndexModel(
                keys=[("key", pymongo.ASCENDING)],
                name="idx_key",
                collation=COLLATION,
            ),
            IndexModel(
                keys=[("dictionary", pymongo.ASCENDING)],
                name="idx_dictionary",
            ),
            IndexModel(
                keys=[("dictionary", pymongo.ASCENDING), ("key", pymongo.ASCENDING)],
                name="idx_dict_key",
            ),
            IndexModel(
                keys=[("identifier", pymongo.ASCENDING)],
                name="idx_identifier",
            ),
            IndexModel(
                keys=[("$**", pymongo.ASCENDING)],
                name="idx_text",
                collation=COLLATION,
            )
        ]

    @before_event(Insert)
    async def init_values(self):
        timestamp = local_now()
        if self.identifier is None:
            self.identifier = uuid4()
        self.timestamp = timestamp
        self.version = 1

    @before_event(Replace, Update, SaveChanges)
    async def update_timestamp(self):
        timestamp = local_now()
        self.timestamp = timestamp
        self.version += 1

    @property
    def document(self) -> Optional[Descriptor]:
        log = logging.getLogger(__name__)
        log.info(f"{__name__}.document")
        try:
            dump = self.model_dump()
            out = Descriptor(**dump)
            log.info(f"{__name__}.document SUCCESS: {type(out)} ")
            return out
        except Exception as e:
            log.error(f"{__name__}.document FAILED: {str(e)}")
            return None

    @classmethod
    async def by_identifier(cls, uuid: Union[str, UUID]) -> Optional[DescriptorDb]:
        query = {'identifier': UUID(uuid)}
        return await cls.find_one(query)

    @classmethod
    async def by_key(cls, dictionary: str, key: str) -> Optional[DescriptorDb]:
        query = {'$and': [{'dictionary': dictionary}, {'$or': [{'key': key}, {'key_alt': key}]}]}
        reply = await cls.find_one(query)
        if reply is None:
            return None
        return reply

    @classmethod
    async def by_query(
            cls, query: Union[dict, None], paging: Union[dict, None], sort: Union[tuple, None]) -> List[Descriptor]:
        reply = await cls.find(query).limit(paging['limit']).skip(paging['skip']).sort(sort).to_list()
        out = []
        for item in reply:
            dump = item.model_dump()
            out_item = Descriptor(**dump)
            out.append(out_item)
        return out

    @classmethod
    async def dictionary(cls, dictionary: str) -> List[Descriptor]:
        query = {'dictionary': dictionary}
        sort = ('key', pymongo.ASCENDING)
        reply = await cls.find(query).limit(1000).skip(0).sort(sort).to_list()
        out = []
        for item in reply:
            dump = item.model_dump()
            out_item = Descriptor(**dump)
            out.append(out_item)
        return out

    @classmethod
    async def export_dictionary(cls, dictionary: str) -> List[DescriptorBase]:
        query = {'dictionary': dictionary}
        sort = ('key', pymongo.ASCENDING)
        reply = await cls.find(query).limit(1000).skip(0).sort(sort).to_list()
        out = []
        for item in reply:
            dump = item.model_dump()
            out_item = DescriptorBase(**dump)
            out.append(out_item)
        return out

    @classmethod
    async def export_all(cls) -> List[DescriptorBase]:
        query = {}
        sort = ('key', pymongo.ASCENDING)
        reply = await cls.find(query).limit(1000).skip(0).sort(sort).to_list()
        out = []
        for item in reply:
            dump = item.model_dump()
            out_item = DescriptorBase(**dump)
            out.append(out_item)
        return out

    async def activate(self, doit=True, save=True):
        if doit is None:
            doit = True
        self.active = doit
        if save:
            reply = await self.replace(None)
            return reply
        return self


class FieldDictionaryImportPostRequest(RootModel):
    root: List[Descriptor]


class ImportPostRequest(RootModel):
    root: List[Descriptor]
